### PR TITLE
Fix .INPUTS fields in Get-ArmorVM

### PR DESCRIPTION
**Pull request by vors**
### Description

Add missed `.INPUTS` annotations.
Fix for https://github.com/tlindsay42/ArmorPowerShell/issues/132

### Related Issue

Fix for https://github.com/tlindsay42/ArmorPowerShell/issues/132

### Motivation and Context

Why is this change required? What problem does it solve?

### Testing Procedure

* Please describe in detail how you tested your changes.
* Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code, et cetera.

### Screenshots (optional)

Please insert screenshots here.

### Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

* [ ] Bug fix (non-breaking change which fixes an issue).
* [ ] New feature (non-breaking change which adds functionality).
* [ ] Breaking change (fix or feature that would cause existing functionality to change).

### Checklist

Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask.  We're here to help!

* [ ] My code follows the code style of this project.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have read the [**CONTRIBUTING**](https://github.com/tlindsay42/ArmorPowerShell/blob/master/.github/CONTRIBUTING.md) document.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vors** [comment]
Sorry, I didn't have patience to go thru the whole PR template. It's probably the longest one I seen :D
Can I humbly suggest to shorten it to reduce the contribution friction?

**Comment by tlindsay42** [comment]
:white_check_mark: [Build ArmorPowerShell 1.0.266-erkjyomq completed](https://ci.appveyor.com/project/tlindsay42/armorpowershell/build/1.0.266-erkjyomq) (commit https://github.com/tlindsay42/ArmorPowerShell/commit/c9659b06e2 by @vors)

**Comment by tlindsay42** [comment]
":white_check_mark: [Build ArmorPowerShell 1.0.266-erkjyomq completed](https://ci.appveyor.com/project/tlindsay42/armorpowershell/build/1.0.266-erkjyomq) (commit https://github.com/tlindsay42/ArmorPowerShell/commit/c9659b06e2 by @vors)"

**Comment by tlindsay42** [comment]
Oh cool!  I didn't know that you could have multiple Inputs entries.  Thanks @vors!

**Pull request merged**
